version: "3.7"
services:
  meilisearch:
    image: getmeili/meilisearch:v1.3
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}
      - MEILI_DB_PATH=${MEILI_DB_PATH:-/data.ms}
    volumes:
      - ./data.ms:/data.ms
    ports:
      - ${MEILI_PORT:-7700}:7700
